name: Mi pipeline para diferentes jobs

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Cancelando ejecuciones en curso
              uses: styfle/cancel-workflow-action@0.9.1
              with:
                  access_token: ${{github.token}}
            - name: Descargando proyecto
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Listando archivos
              run: ls -l
            - name: Configurando Node
              uses: actions/setup-node@v4
              with:
                  node-version: "16"
            - name: Instalando dependencias NPM
              run: npm install --force --no-audit --no-fund --no-optional
            - name: Ejecutando Linter
              run: npm run eslint
            - name: Generando build
              run: npm run build
            - name: Ejecutando tests unitarios con Jest
              run: npm run test
            - name: Preparando app para pruebas
              run: npm run start-test &
            - name: Preparando aplicación
              run: sleep 5
            - name: Ejecutando test E2E con Cypress
              run: npm run test:e2e
