name: Mi pipeline para diferentes jobs

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Descargando proyecto
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Listando archivos
              run: ls -l
            - name: Configurando Node
              uses: actions/setup-node@v4
              with:
                  node-version: "16"
            - name: Instalando dependencias npm
              run: npm install --force --no-audit --no-fund --no-optional
            - name: Ejecutando Lint
              run: npm run eslint
            - name: Generando build
              run: npm run build
            - name: Ejecutando tests
              run: npm run test
